#-- how to scroll after C-b
# half-page UP      -> C-u
# half-page DOWN    -> C-d
# go up history     -> gg
# go bottom history -> G
# exit scroll mode  -> q

#-- how to reload config 
# 1. C-b r
# 2. : (enter command mode just like vim)
# 3. source-file ~/.tmux.conf

# navigate like vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set scroll to use vim motion
set-window-option -g mode-keys vi
